### ISSUE TITLE
Existing EE Members not authenticating

### ISSUE THREAD

**Issue by BakerCo** [drawmyattention/expauth#2]
Am I missing something? I just stepped through the whole auth process with xdebug and the two hash values do not match on the existing EE members. I have followed the setup instructions and I'm using the latest Laravel 5.1. Something I noticed when stepping through is that the salt is not being set from the members' table to the model when rehashing... could this be the issue?

**Comment by BakerCo** [comment]
Ok, this turned out to be that this package is referencing App/User in the ServiceProvider, I had changed the namespace to something else causing this to fail. Switching the namespace resolved my issue. It would be nice to force the user to implement an interface or something so that a namespace won't break when checking 'instanceof'.

**Comment by amochohan** [comment]
Agreed. I believe it was false optimisation based on Scrutinizer complaining about the User instance type which actually is doing more harm than good.

Feel free to send a PR.
